**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
nul_vector = np.zeros(10)
nul_vector[4] = 1
nul_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
rand_array = np.random.random(a*b)
print(rand_array, end="\n")
print(f"Average: {np.average(rand_array)}")
print(f"Average: {rand_array.mean()}")          

Enter first number: 5
Enter second number: 2
[0.84535443 0.94615659 0.47929066 0.16189003 0.53061288 0.36918382
 0.85756137 0.13863125 0.46380473 0.12902386]
Average: 0.4921509612271181
Average: 0.4921509612271181


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [4]:
#Code here
def border_array(a, b):
    arr = np.zeros(a*b, dtype=int).reshape(a,b)
    arr[0, :] = 1
    arr[-1, :] = 1
    arr[:, 0] = 1
    arr[:, -1] = 1
    print(arr)
    
border_array(5,6)


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [5]:
#Code here
# vector = np.linspace(0, 1, 12)
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [6]:
#Code here
# id_mat = np.eye(3)
# print(res)

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [7]:
#Code here
mat = np.ones(25, dtype=int). reshape(5,5)
mat[:] = np.arange(0,5)
print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [8]:
#code here
point = np.array([2,3])
rand_cord = np.random.randint(1, 101, size=(10,2))

# Calculate the Euclidean distance for each point in the random vector from the given point
distance = np.linalg.norm(rand_cord - point, axis=1)

# Convert distances to integers
distance = distance.astype(int)

print(point)
print(rand_cord)
print(distance)

[2 3]
[[ 1 85]
 [64 35]
 [15 22]
 [99 37]
 [77 63]
 [77 13]
 [17  1]
 [15 47]
 [46  5]
 [89 84]]
[ 82  69  23 102  96  75  15  45  44 118]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [9]:
#Code here
import numpy as np

# Create a numpy array with shape (6, 7, 8)
array_shape = (6, 7, 8)
array_size = np.prod(array_shape)

flat_index = 99  # Note that Python uses 0-based indexing, so the 100th element has index 99

# Find the index tuple (x, y, z) for the given flat index
index_tuple = np.unravel_index(flat_index, array_shape)

print("Index Tuple (x, y, z):", index_tuple)


Index Tuple (x, y, z): (1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [10]:
#Code here
given = [1, 2, 3, 4, -8, -10]
rev_array = np.array(given, dtype=float)
print(rev_array[-1::-1])

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [11]:
#Code here
arr = np.array([1, 2, 3, 4, 5])
print(f"elements_count: {arr.size}")

elements_count: 5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [12]:
#Code here
import numpy as np

def softmax(x):
    # Check if the input is a 1D array
    if len(x.shape) != 1:
        raise ValueError("Input must be a 1D array.")

    # Calculate the exponential of each element
    exp_x = np.exp(x - np.max(x))  # Subtracting the maximum for numerical stability

    # Calculate the softmax probabilities
    softmax_values = exp_x / np.sum(exp_x)

    return softmax_values

# Example usage:
input_array = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])

result = softmax(input_array)

print("Input Array:")
print(input_array)
print("\nSoftmax Result:")
print(result)


Input Array:
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]

Softmax Result:
[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [13]:
#Coder here
import numpy as np
def vertical_stacking(*arrays):    
    if any(not isinstance(arr, np.ndarray) for arr in arrays):
        # The `if any(...)` construct is used to check if at least one element in the iterable provided to `any()` is `True`. 
        raise ValueError("All arguments must be numpy arrays")
                         
    result = np.vstack((arrays))
    print(result)

arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
arr3 = np.arange(21,31).reshape(2,5)

arr4 = [1, 2, 3, 4]
arr5 = [5, 6, 7, 8]
arr6 = [9, 10, 11, 12]

a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

try:
#     vertical_stacking(arr1, arr2, arr3)
    vertical_stacking(arr4, arr5, arr6)
#     vertical_stacking(a, b, c)
except ValueError as e:
    print(e)


All arguments must be numpy arrays


In [14]:
# Just for understanding not the part of assignment
a = 2
b = 2.5
c = 3
lst1 = [2, 2.5, 3]
lst2 = [1, 2, 3]
lst3 = ["1", "2", "3"]

try:
    if any(not isinstance(num, int) for num in lst1):
        raise ValueError("Must be integer")
    print("No error")
        
except ValueError as e:
    print(e)



Must be integer


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [15]:
#Code here
import numpy as np
def date_array(start_date, end_date):
    
    end = np.datetime64(end_date) + np.timedelta64(1, "D") # To make end date include
    arr = np.arange(start_date, end, dtype="datetime64[D]")
    print(arr)

date_array('2020-11-25', '2020-11-30')


['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [16]:
#code here
arr = np.random.random((3,4))
print("Original Array")
print(arr, "\n")
print("Subtracted Array from row mean")
for i in range(len(arr)):
    row_mean = arr[i].mean()  
    result = row_mean - arr[i]
    print(result)   
  

Original Array
[[0.73667832 0.85387892 0.91012262 0.33171461]
 [0.17574551 0.02946556 0.79896454 0.51943665]
 [0.5378227  0.94335726 0.01032489 0.31082225]] 

Subtracted Array from row mean
[-0.0285797  -0.14578031 -0.202024    0.37638401]
[ 0.20515756  0.3514375  -0.41806147 -0.13853359]
[-0.08724092 -0.49277549  0.44025689  0.13975953]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [17]:
#Code here
arr = np.array([0,1,2,3,4,5,6,8,9,10]).reshape(5,2)
print(arr, "\n")

result = np.concatenate((arr[0:, 1:], arr[0:, :1]), axis=1)
print(result)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  8]
 [ 9 10]] 

[[ 1  0]
 [ 3  2]
 [ 5  4]
 [ 8  6]
 [10  9]]


In [18]:
arr = np.array([[1,2,3,], [4,5,6], [7,8,9]])

x = arr[:, 0:1].copy()
y = arr[:, 1:2].copy()
z = arr[:, 2:3].copy()

arr[:, 0:1] = z
arr[:, 1:2] = x
arr[:, 2:3] = y
print(arr)

[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [19]:
arr = np.array([[1,2,3,], 
                [4,5,6], 
                [7,8,9]])

arr[:, [0,1]] = arr[:, [1,0]]
print(arr)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [20]:
import numpy as np

# Create a sample 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Print the original array for debugging
print("Original Array:")
print(original_array)

# Column names to swap
column1_name = 1
column2_name = 2

# Check if the column names exist in the first row
if column1_name not in original_array[0] or column2_name not in original_array[0]:
    print(f"Error: One or both of the column names ({column1_name}, {column2_name}) not found.")
else:
    # Find the indices of the columns
    column1_index = np.where(original_array[0] == column1_name)[0][0]
    column2_index = np.where(original_array[0] == column2_name)[0][0]

    # Swap columns
    original_array[:, [column1_index, column2_index]] = original_array[:, [column2_index, column1_index]]

    # Print the result
    print("\nArray after swapping columns:")
    print(original_array)



Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping columns:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [21]:
#Code here
arr = np.array([1,2,3,4,5,6])
for ind, val in np.ndenumerate(arr):
    if val % 2 != 0:
        arr[ind] = -1
print(arr)

[-1  2 -1  4 -1  6]


In [22]:
arr = np.arange(10).reshape(2,5)
print("Original Array")
print(arr)
for ind, val in np.ndenumerate(arr):
    if val % 2 != 0:
        arr[ind] = -1
        
print("\nChanged Array")
print(arr)


Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]

Changed Array
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [23]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
for ind, val in np.ndenumerate(arr):
    if val % 2 != 0:
        arr[ind] = -1
print(arr)

[[[-1  2 -1]
  [ 4 -1  6]]

 [[-1  8 -1]
  [10 -1 12]]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [24]:
#Code here
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
result = np.array([np.max(a), np.max(b)])
print(result)

[8 7]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [25]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2653, 9693, 9562, 4439, 6870],
       [5304, 8615, 5906, 1764, 4819],
       [3383,  597, 7603, 3147, 2339],
       [5294, 6264, 5649, 5287, 3668],
       [ 639, 9320, 3578,  310, 7241],
       [1100, 4203, 6790, 6944, 8023],
       [8183, 5592, 7268, 6703,  776],
       [6334, 6607, 2912, 6063, 6490]])

In [26]:
#Code here
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
numerator = arr1 - np.min(arr1)
denominator = np.max(arr1) - np.min(arr1)

norm_array = numerator / denominator

print("Original Array")
print(arr1)

print("\nNormalized Array")
print(norm_array)

Original Array
[[6073 5312 1846 4888 6019]
 [6518 1518 9302 4667 9806]
 [ 516 7276 8077 1322 3255]
 [9218 1681  123 3082  935]
 [6519 1136 2440 8757 1606]
 [3228 2783 7113 2720 8373]
 [1612 7856 9891 8843   37]
 [5001 1213 7059 4950 3558]]

Normalized Array
[[0.61254313 0.53531561 0.18358027 0.4922874  0.60706312]
 [0.65770246 0.1502943  0.94022732 0.46985996 0.99137406]
 [0.0486097  0.73462553 0.81591232 0.1304039  0.32656789]
 [0.93170286 0.1668358  0.00872742 0.30901157 0.09113051]
 [0.65780394 0.11152831 0.24386036 0.88491983 0.15922468]
 [0.32382789 0.27866856 0.71808403 0.27227522 0.84595088]
 [0.15983357 0.79348488 1.         0.89364725 0.        ]
 [0.50375482 0.1193424  0.71260402 0.49857926 0.35731683]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [27]:
#Code here
import numpy as np
def largest_item(array, number):
    
    if isinstance(array, np.ndarray) and number <= len(array):
        array.sort()
        print(array[-number])
    else:
        raise ValueError ("Only numpy array and number should be less than length of an array!")
    
arr = np.array([12,34,40,7,1,0])
arr1 = [12,34,40,7,1,0]

try:
    largest_item(arr, 2)
except ValueError as e:
    print(e)

34


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [34]:
#code here

a = np.array([1,2,3])
len_array = len(a)
for i in np.nditer(a):
    print(i)

1
2
3
