In [1]:
import numpy as np

In [2]:
first_numpy_array = np.array([1,2,3,4])

In [3]:
print(first_numpy_array)

[1 2 3 4]


In [4]:
array_with_zeros = np.zeros((3,3))

In [5]:
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
array_with_ones = np.ones((3,3))

In [9]:
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
array_with_empty = np.empty((2,3))

In [13]:
print(array_with_empty)

[[4.67034283e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [16]:
np_arrage = np.arange(12)

In [17]:
print(np_arrage)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
np_arrage.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
#Linspace for linearly (equal) spaced data elements (1st element = 1, Last element = 6, Total number of equidistant element = 5)
np_linspace = np.linspace(1,6,5)

In [23]:
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [24]:
# One diemensional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
# Two Dimenesional array
twoD_array = oneD_array.reshape(3,5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [28]:
# Three Dimensional array
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
