Shape Manipulation

In [2]:
import numpy as np

In [3]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [4]:
# Flatten the data set
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [5]:
# Reshaping data set to 3 rows and 4 columns
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [6]:
# Reshaping data set to 2 rows and 6 columns
new_cyclist_trials.reshape(2,6)

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [7]:
# Splits the array into 2, contain 2 rows and 3 columns
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [8]:
new_cyclist_1 = np.array([10,15,17,26,13,19])

In [9]:
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [11]:
# Stack two arrays together
np.hstack((new_cyclist_1,new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])