In [1]:
import numpy as np

Create one dimensional array with alias as np and perform the following methods:
np.zeros(),
np.ones(),
np.empty(),
np.arrange(),
np.reshape(),
np.linspace()

In [3]:
first_numpy_array = np.array([1,2,3,4,5,6])

In [5]:
print (first_numpy_array)

[1 2 3 4 5 6]


In [6]:
array_with_zeros = np.zeros((3,3))

In [7]:
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
array_with_ones = np.ones((3,3))

In [10]:
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
array_with_empty = np.empty((2,3))

In [17]:
print(array_with_empty)

[[4.68131111e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [19]:
np_arrange = np.arange(12)

In [20]:
print(np_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
np_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np_linspace = np.linspace(1,6,5)

In [27]:
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [28]:
oneD_array = np.arange(15)

In [29]:
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [32]:
twod_array = oneD_array.reshape(3,5)

In [33]:
print(twod_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
threed_array = np.arange(27).reshape(3,3,3)

In [35]:
print(threed_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [42]:
numpy_array_loop = np.array([_ for _ in range(1,10)]) #_ is used in loop when there is no other use of variable

In [43]:
print(numpy_array_loop)

[1 2 3 4 5 6 7 8 9]


In [44]:
print(numpy_array_loop.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
numpy_array_loop = np.array([_ for _ in range (1,13)])

In [46]:
print(numpy_array_loop)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [47]:
numpy_array_loop.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
numpy_array_loop.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
numpy_array_loop.reshape(2,2,4)

ValueError: cannot reshape array of size 12 into shape (2,2,4)

In [51]:
numpy_array_loop.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [53]:
numpy_array_loop.reshape(2,2,-1) # -1 automatically calculte its last dimesion into 3 it very usefull to when we are using dynamic data set

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
# Flatten the array with -1
num_arr = numpy_array_loop.reshape(3,2,2)

In [57]:
num_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([8,9,10])

In [60]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
B

array([ 8,  9, 10])

In [64]:
np.add(A,B)

array([[ 9, 11, 13],
       [12, 14, 16]])

In [66]:
np.subtract(B,A)

array([[7, 7, 7],
       [4, 4, 4]])

In [67]:
np.multiply(A,B)

array([[ 8, 18, 30],
       [32, 45, 60]])

In [68]:
np.divide(A,B)

array([[0.125     , 0.22222222, 0.3       ],
       [0.5       , 0.55555556, 0.6       ]])

In [69]:
np.power(A,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [70]:
np.power(A,B)

array([[       1,      512,    59049],
       [   65536,  1953125, 60466176]])

Condition Statement

In [76]:
X = np.array([_ for _ in range(1,13)])

In [77]:
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
np.where(X%2 ==0, "Even", "Odd")

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even'], dtype='<U4')

In [84]:
condList = [X<5, X>5]
choiceList = [X**2, X**3]

In [85]:
np.select(condList, choiceList, default=X)

array([   1,    4,    9,   16,    5,  216,  343,  512,  729, 1000, 1331,
       1728])

In [95]:
a = X.reshape(3,4)
print(a)
np.min(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


1

In [93]:
np.amin(a)

1

In [94]:
np.amin(a, axis = 0) # Vertical

array([1, 2, 3, 4])

In [99]:
np.amin(a,axis=1) # Horizontal

array([1, 5, 9])

In [96]:
np.max(a)

12

In [97]:
np.amax(a, axis=0) # Vertical

array([ 9, 10, 11, 12])

In [98]:
np.amax(a,axis=1) # Horizontal

array([ 4,  8, 12])

In [101]:
np.median(a)

6.5

In [102]:
np.mean(a)

6.5

In [103]:
np.std(a)

3.452052529534663

In [104]:
np.var(a)

11.916666666666666

In [106]:
np.percentile(a, 50)

6.5

In [107]:
deg = np.array([0,30,45,60,90])

In [108]:
np.sin(deg * np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [109]:
np.cos(deg * np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [110]:
np.tan(deg * np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

We also have the inverse of the tignometric function i.e. arcsin. arccos, arctan

In [111]:
arr = np.array([0.1, 0.8, -2.2, -9.87])

In [112]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [113]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])

Indexing in numpy array

In [123]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [124]:
array_1d[0]

1

In [125]:
array_1d[1]

2

In [126]:
array_1d[-3]

4

In [127]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
array_2d[0,0]

1

In [129]:
array_2d[0,1]

2

In [130]:
array_2d[0,-1]

3

In [132]:
array_2d[1,1]

5

In [133]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [136]:
array_3d[0,1,2] # Print 3rd element in the 2nd row

6

In [138]:
array_3d[1,1,2] # Print 3rd element in the 4th row

12

In [139]:
array_3d[1,1,-2] # Print 2rd element in the 4th row

11

Slicing in numpy array

In [140]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [141]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [142]:
array_1d[2:5]

array([3, 4, 5])

In [143]:
array_1d[-3:-1]

array([4, 5])

In [144]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
array_2d[1,1:]

array([5, 6])

In [146]:
array_2d[-2,-2:-1]

array([2])

In [147]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

In [148]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [149]:
array_3d[0,1:,1:]

array([[5, 6]])